-- Creo warehouse
CREATE WAREHOUSE IF NOT EXISTS WH_RETAIL
  WAREHOUSE_SIZE = 'XSMALL' -- Tamaño = 1 nodo, no necesito mas
  AUTO_SUSPEND = 60         -- Si no se esta usando se suspende a los 60 segundos
  AUTO_RESUME = TRUE;       -- Si llega un nuevo query se levanta automaticamente

-- Creo database
CREATE DATABASE IF NOT EXISTS DB_DEV;

-- Creo schema
CREATE SCHEMA IF NOT EXISTS DB_DEV.SILVER_STAGING;

-- Creo rol y le doy sus permisos
CREATE ROLE IF NOT EXISTS ROLE_DATABRICKS_ETL;

GRANT USAGE ON WAREHOUSE WH_RETAIL TO ROLE ROLE_DATABRICKS_ETL; -- Permiso sobre WH
GRANT USAGE ON DATABASE DB_DEV TO ROLE ROLE_DATABRICKS_ETL;     -- Permiso sobre DB
GRANT USAGE, CREATE TABLE, CREATE STAGE                         -- Permisos sobre Schema
  ON SCHEMA DB_DEV.SILVER_STAGING
  TO ROLE ROLE_DATABRICKS_ETL;

-- Creo usuario y le doy el rol creado
CREATE USER IF NOT EXISTS USER_DATABRICKS_ETL
  PASSWORD = /*PASSWORD*/
  DEFAULT_ROLE = ROLE_DATABRICKS_ETL         -- Role default si tiene muchos
  DEFAULT_WAREHOUSE = WH_RETAIL              -- WH default si tiene varias
  DEFAULT_NAMESPACE = DB_DEV.SILVER_STAGING; -- Schema default si tiene varios
  
GRANT ROLE ROLE_DATABRICKS_ETL TO USER USER_DATABRICKS_ETL;
ALTER USER USER_DATABRICKS_ETL SET DEFAULT_ROLE = ROLE_DATABRICKS_ETL;                                             -- Por si acaso
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DB_DEV.SILVER_STAGING TO ROLE ROLE_DATABRICKS_ETL; -- Para proximas tablas

CREATE TABLE IF NOT EXISTS DB_DEV.SILVER_STAGING.EVENTS_LANDING (
  EVENT_TIME    TIMESTAMP_NTZ,
  EVENT_DATE    DATE,
  LOAD_DATE     TIMESTAMP_NTZ,

  PRICE         NUMBER(10,2),
  PRODUCT_ID    NUMBER(38,0),
  USER_ID       NUMBER(38,0),
  CATEGORY_ID   NUMBER(38,0),

  EVENT_TYPE    VARCHAR,
  CATEGORY_CODE VARCHAR,
  BRAND         VARCHAR,
  USER_SESSION  VARCHAR
);

ALTER TABLE DB_DEV.SILVER_STAGING.EVENTS_LANDING CLUSTER BY (EVENT_DATE); -- Para particionar