-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~~~~~~ Conecto Databricks con Snowflake ~~~~~~~
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- Creo warehouse
CREATE WAREHOUSE IF NOT EXISTS WH_RETAIL
  WAREHOUSE_SIZE = 'XSMALL' -- Tamaño = 1 nodo, no necesito mas
  AUTO_SUSPEND = 60         -- Si no se esta usando se suspende a los 60 segundos
  AUTO_RESUME = TRUE;       -- Si llega un nuevo query se levanta automaticamente

-- Creo database
CREATE DATABASE IF NOT EXISTS DB_DEV;

-- Creo schema
CREATE SCHEMA IF NOT EXISTS DB_DEV.SILVER_STAGING;

-- Creo rol y le doy sus permisos
CREATE ROLE IF NOT EXISTS ROLE_DATABRICKS_ETL;

GRANT USAGE ON WAREHOUSE WH_RETAIL TO ROLE ROLE_DATABRICKS_ETL; -- Permiso sobre WH
GRANT USAGE ON DATABASE DB_DEV TO ROLE ROLE_DATABRICKS_ETL;     -- Permiso sobre DB
GRANT USAGE, CREATE TABLE, CREATE STAGE                         -- Permisos sobre Schema
  ON SCHEMA DB_DEV.SILVER_STAGING
  TO ROLE ROLE_DATABRICKS_ETL;

-- Creo usuario y le doy el rol creado
CREATE USER IF NOT EXISTS USER_DATABRICKS_ETL
  PASSWORD = /*PASSWORD*/
  DEFAULT_ROLE = ROLE_DATABRICKS_ETL         -- Role default si tiene muchos
  DEFAULT_WAREHOUSE = WH_RETAIL              -- WH default si tiene varias
  DEFAULT_NAMESPACE = DB_DEV.SILVER_STAGING; -- Schema default si tiene varios
  
GRANT ROLE ROLE_DATABRICKS_ETL TO USER USER_DATABRICKS_ETL;
ALTER USER USER_DATABRICKS_ETL SET DEFAULT_ROLE = ROLE_DATABRICKS_ETL;                                             -- Por si acaso
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DB_DEV.SILVER_STAGING TO ROLE ROLE_DATABRICKS_ETL; -- Para proximas tablas

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~~~~~~~~~~~~ Configuro cosas dbt ~~~~~~~~~~~~~~
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- Creo EVENTS_LANDING
CREATE TABLE IF NOT EXISTS DB_DEV.SILVER_STAGING.EVENTS_LANDING (
  EVENT_TIME    TIMESTAMP_NTZ,
  EVENT_DATE    DATE,
  LOAD_DATE     TIMESTAMP_NTZ,

  PRICE         NUMBER(10,2),
  PRODUCT_ID    NUMBER(38,0),
  USER_ID       NUMBER(38,0),
  CATEGORY_ID   NUMBER(38,0),

  EVENT_TYPE    VARCHAR,
  CATEGORY_CODE VARCHAR,
  BRAND         VARCHAR,
  USER_SESSION  VARCHAR
);

ALTER TABLE DB_DEV.SILVER_STAGING.EVENTS_LANDING CLUSTER BY (EVENT_DATE); -- Para particionar

-- Creo REJECTED_EVENTS
CREATE TABLE IF NOT EXISTS DB_DEV.SILVER_STAGING.REJECTED_EVENTS (
  EVENT_TIME    TIMESTAMP_NTZ,
  EVENT_DATE    DATE,
  LOAD_DATE     TIMESTAMP_NTZ,

  PRICE         NUMBER(10,2),
  PRODUCT_ID    NUMBER(38,0),
  USER_ID       NUMBER(38,0),
  CATEGORY_ID   NUMBER(38,0),

  EVENT_TYPE    VARCHAR,
  CATEGORY_CODE VARCHAR,
  BRAND         VARCHAR,
  USER_SESSION  VARCHAR,

  REJECT_REASON VARCHAR,
  REJECTED_AT   TIMESTAMP_NTZ
);

-- Creo LOADED_DATES
CREATE TABLE IF NOT EXISTS DB_DEV.SILVER_STAGING.LOADED_DATES (
  EVENT_DATE    DATE,
  LOAD_DATE     TIMESTAMP_NTZ,
  ROWS_LOADED   NUMBER(38,0),
  ROWS_REJECTED NUMBER(38,0)
);

-- Configuraciones para dbt:
-- Creo schema y rol
CREATE SCHEMA IF NOT EXISTS DB_DEV.ANALYTICS_DEV;
CREATE ROLE IF NOT EXISTS ROLE_DBT_DEV;

-- Permisos sobre warehouse, database y schema (ANALYTICS_DEV) al rol
GRANT USAGE ON WAREHOUSE WH_RETAIL TO ROLE ROLE_DBT_DEV;
GRANT USAGE ON DATABASE DB_DEV TO ROLE ROLE_DBT_DEV;
GRANT USAGE ON SCHEMA DB_DEV.ANALYTICS_DEV TO ROLE ROLE_DBT_DEV;
GRANT CREATE TABLE ON SCHEMA DB_DEV.ANALYTICS_DEV TO ROLE ROLE_DBT_DEV;
GRANT CREATE VIEW ON SCHEMA DB_DEV.ANALYTICS_DEV TO ROLE ROLE_DBT_DEV;

-- Permisos sobre schema (SILVER_STAGING)
GRANT USAGE ON SCHEMA DB_DEV.SILVER_STAGING TO ROLE ROLE_DBT_DEV;
GRANT SELECT ON ALL TABLES IN SCHEMA DB_DEV.SILVER_STAGING TO ROLE ROLE_DBT_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DB_DEV.SILVER_STAGING TO ROLE ROLE_DBT_DEV;

-- Creo usuario para dbt
CREATE USER IF NOT EXISTS USER_DBT
  PASSWORD = /*PASSWORD*/
  DEFAULT_ROLE = ROLE_DBT_DEV
  DEFAULT_WAREHOUSE = WH_RETAIL
  DEFAULT_NAMESPACE = DB_DEV.ANALYTICS_DEV
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE ROLE_DBT_DEV TO USER USER_DBT;

-- Creo CTL_PROCESSED_DATES
CREATE TABLE IF NOT EXISTS DB_DEV.ANALYTICS_DEV.CTL_PROCESSED_DATES (
  EVENT_DATE    DATE NOT NULL,
  PROCESSED_AT  TIMESTAMP_NTZ NOT NULL,
  ROWS_LOADED   NUMBER
);

GRANT SELECT ON ALL TABLES IN SCHEMA DB_DEV.ANALYTICS_DEV TO ROLE ROLE_DBT_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DB_DEV.ANALYTICS_DEV TO ROLE ROLE_DBT_DEV;
GRANT INSERT ON TABLE DB_DEV.ANALYTICS_DEV.CTL_PROCESSED_DATES TO ROLE ROLE_DBT_DEV;